apiVersion: apps/v1
kind: Deployment
metadata:
  name: detector-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detector-app
  template:
    metadata:
      labels:
        app: detctor-app
    spec:
      containers:
      - name: detector-container
        image: spam-email:latest
        ports:
        - containerPort: 80
